use std::env;
use std::fs;
use std::path::PathBuf;

use serde_json::Value;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let artifact = manifest.join("../protocol.json");
    println!("cargo:rerun-if-changed={}", artifact.display());

    let document: Value =
        serde_json::from_str(&fs::read_to_string(&artifact).expect("read protocol.json"))
            .expect("parse protocol.json");
    let generated = generate(&document);
    let output = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("protocol.rs");
    fs::write(output, generated).expect("write generated protocol constants");
}

fn generate(document: &Value) -> String {
    let version = document["protocolVersion"]
        .as_u64()
        .expect("protocolVersion must be an unsigned integer");
    let rejections = strings(&document["rejectionCodes"], "rejectionCodes");
    let phases = strings(&document["phases"], "phases");
    let settlement_outcomes = strings(&document["settlementOutcomes"], "settlementOutcomes");
    let faults = document["faultEventTokens"]
        .as_object()
        .expect("faultEventTokens must be an object");
    let cheats = document["cheatArgumentShapes"]
        .as_array()
        .expect("cheatArgumentShapes must be an array");

    let mut code = String::from(
        "// Generated by cli/build.rs from protocol.json. Do not edit.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         enum ProtocolArgumentKind { Boolean, Integer, String }\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         struct ProtocolArgumentSpec {\n\
             name: &'static str,\n\
             kind: ProtocolArgumentKind,\n\
             optional: bool,\n\
         }\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         struct CheatArgumentShape {\n\
             name: &'static str,\n\
             arguments: &'static [ProtocolArgumentSpec],\n\
         }\n\n",
    );
    code.push_str(&format!(
        "#[allow(dead_code)]\nconst PROTOCOL_VERSION: u64 = {version};\n"
    ));
    emit_strings(&mut code, "REJECTION", "REJECTION_CODES", &rejections);
    emit_strings(&mut code, "PHASE", "PHASES", &phases);
    emit_settlement_outcome(&mut code, &settlement_outcomes);

    for (name, value) in faults {
        let value = value.as_str().expect("fault token must be a string");
        let constant = constant_name("FAULT_EVENT", name);
        code.push_str(&format!(
            "#[allow(dead_code)]\nconst {constant}: &str = {value:?};\n"
        ));
    }
    code.push_str("#[allow(dead_code)]\nconst FAULT_EVENT_TOKENS: &[(&str, &str)] = &[\n");
    for (name, value) in faults {
        value.as_str().expect("fault token must be a string");
        let constant = constant_name("FAULT_EVENT", name);
        code.push_str(&format!("    ({name:?}, {constant}),\n"));
    }
    code.push_str("];\n");

    code.push_str("const CHEAT_ARGUMENT_SHAPES: &[CheatArgumentShape] = &[\n");
    for cheat in cheats {
        let name = cheat["name"].as_str().expect("cheat name must be a string");
        let arguments = cheat["arguments"]
            .as_array()
            .expect("cheat arguments must be an array");
        code.push_str(&format!(
            "    CheatArgumentShape {{ name: {name:?}, arguments: &[\n"
        ));
        for argument in arguments {
            let argument_name = argument["name"]
                .as_str()
                .expect("argument name must be a string");
            let kind = match argument["type"].as_str() {
                Some("boolean") => "Boolean",
                Some("integer") => "Integer",
                Some("string") => "String",
                other => panic!("unsupported protocol argument type: {other:?}"),
            };
            let optional = argument["optional"].as_bool().unwrap_or(false);
            code.push_str(&format!(
                "        ProtocolArgumentSpec {{ name: {argument_name:?}, \
                 kind: ProtocolArgumentKind::{kind}, optional: {optional} }},\n"
            ));
        }
        code.push_str("    ] },\n");
    }
    code.push_str("];\n");
    code
}

fn emit_settlement_outcome(code: &mut String, values: &[&str]) {
    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\nenum SettlementOutcome {\n");
    for value in values {
        code.push_str(&format!("    {},\n", variant_name(value)));
    }
    code.push_str("}\nimpl SettlementOutcome {\n");
    code.push_str("    fn from_value(value: &serde_json::Value) -> Option<Self> {\n");
    code.push_str("        match value.as_str() {\n");
    for value in values {
        code.push_str(&format!(
            "            Some({value:?}) => Some(Self::{}),\n",
            variant_name(value)
        ));
    }
    code.push_str("            _ => None,\n        }\n    }\n");
    code.push_str(
        "    fn is_replayable(self) -> bool {\n\
             matches!(self, Self::Settled | Self::NextDecision)\n\
         }\n\
         fn reached_boundary(self) -> bool {\n\
             self != Self::Timeout\n\
         }\n\
         }\n",
    );
}

fn strings<'a>(value: &'a Value, field: &str) -> Vec<&'a str> {
    value
        .as_array()
        .unwrap_or_else(|| panic!("{field} must be an array"))
        .iter()
        .map(|item| {
            item.as_str()
                .unwrap_or_else(|| panic!("{field} entries must be strings"))
        })
        .collect()
}

fn emit_strings(code: &mut String, prefix: &str, name: &str, values: &[&str]) {
    for value in values {
        let constant = constant_name(prefix, value);
        code.push_str(&format!(
            "#[allow(dead_code)]\nconst {constant}: &str = {value:?};\n"
        ));
    }
    code.push_str(&format!(
        "#[allow(dead_code)]\nconst {name}: &[&str] = &[\n"
    ));
    for value in values {
        code.push_str(&format!("    {},\n", constant_name(prefix, value)));
    }
    code.push_str("];\n");
}

fn constant_name(prefix: &str, value: &str) -> String {
    let mut result = format!("{prefix}_");
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            result.push(character.to_ascii_uppercase());
        } else if !result.ends_with('_') {
            result.push('_');
        }
    }
    while result.ends_with('_') {
        result.pop();
    }
    result
}

fn variant_name(value: &str) -> String {
    value
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut characters = part.chars();
            let first = characters
                .next()
                .expect("non-empty protocol enum segment")
                .to_ascii_uppercase();
            format!("{first}{}", characters.as_str().to_ascii_lowercase())
        })
        .collect()
}
